apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: icculus
  annotations:
    github.com/project-slug: salty-pig/icculus
spec:
  type: other
  lifecycle: unknown
  owner: user:development/guest
